handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/(.*)/(.*)'
  static_files: '/\1/\2'
  upload: '/(.*)'
- url: '/(.*)'
  static_files: /\1.html
  upload: '/(.*)'
- error_handlers:
  - file: error.html
