handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/404.html'
  static_files: '404.html'
  upload: '.*'
- url: '/(.*)/(.*)'
  static_files: '/\1/\2'
  upload: '/(.*)'
- url: '/(.*)'
  static_files: /\1.html
  upload: '/(.*)'
