handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/404.html'
  static_files: '404.html'
  upload: '.*'
- url: '/sitemap3'
  static_files: 'sitemap.sh'
  upload: '.*'
- url: '/robots.txt'
  static_files: 'robots.txt'
  upload: '.*'
- url: '/sitemap.xml'
  static_files: 'sitemap.xml'
  upload: '.*'
- url: '/(.*)/(.*)'
  static_files: '/\1/\2'
  upload: '/(.*)'
- url: '/(.*)'
  static_files: /\1.html
  upload: '/(.*)'
